<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_message_check_status.proto

namespace GPBMetadata\Site;

class ApiMessageCheckStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Message::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab6020a23736974652f6170695f6d6573736167655f636865636b5f7374" .
            "617475732e70726f746f120473697465225a0a1c4170694d657373616765" .
            "436865636b5374617475735265717565737412110a096d65737361676549" .
            "6418012003280912270a08726f6f6d5479706518022001280e32152e636f" .
            "72652e4d657373616765526f6f6d54797065224b0a1d4170694d65737361" .
            "6765436865636b537461747573526573706f6e7365122a0a0d7374617475" .
            "734d65737361676518012003280b32132e636f72652e5374617475734d65" .
            "737361676542580a13636f6d2e7a616c792e70726f746f2e736974655a2f" .
            "6769746875622e636f6d2f6475636b636861742f6475636b636861742d67" .
            "6174657761792f70726f746f2f73697465ca020f5a616c795c50726f746f" .
            "5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

