<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: site/api_site_login.proto

namespace GPBMetadata\Site;

class ApiSiteLogin
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98030a19736974652f6170695f736974655f6c6f67696e2e70726f746f" .
            "1204736974652297010a13417069536974654c6f67696e52657175657374" .
            "12140a0c70726553657373696f6e496418012001280912150a0d64657669" .
            "63655075626b50656d18022001280912110a096c6f67696e4e616d651803" .
            "2001280912120a0a69735265676973746572180420012808122c0a0b7573" .
            "6572437573746f6d7318052003280b32172e636f72652e437573746f6d55" .
            "73657250726f66696c6522790a14417069536974654c6f67696e52657370" .
            "6f6e736512110a0973657373696f6e496418012001280912250a0770726f" .
            "66696c6518022001280b32142e636f72652e416c6c5573657250726f6669" .
            "6c6512270a06637573746f6d18032003280b32172e636f72652e43757374" .
            "6f6d5573657250726f66696c6542580a13636f6d2e7a616c792e70726f74" .
            "6f2e736974655a2f6769746875622e636f6d2f6475636b636861742f6475" .
            "636b636861742d676174657761792f70726f746f2f73697465ca020f5a61" .
            "6c795c50726f746f5c53697465620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

