<?php
/**
 * Created by PhpStorm.
 * User: zhangjun
 * Date: 20/08/2018
 * Time: 4:48 PM
 */

class Page_JsController extends  HttpBaseController
{
    public $callBackSuccess;
    public $userInfo = false;
    public $callBackFail;
    public $isReqType;

    public  function doIndex()
    {
//        parent::doIndex(); // TODO: Change the autogenerated stub
        $this->index();
    }


    public function index()
    {
        header('Access-Control-Allow-Origin: *');
        $loginName = isset($_GET['loginName']) ? trim($_GET['loginName']) : "";

        $this->callBackSuccess = isset($_GET['success_callback']) ? $_GET['success_callback'] : "";
        $this->callBackFail    = isset($_GET['fail_callback']) ? $_GET['fail_callback'] : "";
        $this->isReqType = isset($_GET['isReqType']) ? $_GET['isReqType'] : "";

        if(!$loginName){
            echo $this->returnBack();
            return;
        }
        $this->userInfo = $this->ctx->SiteUserTable->getUserByLoginName($loginName);

        echo $this->returnBack();
        return;
    }

    public function returnBack()
    {
        if($this->isReqType == "proxy") {
            if($this->userInfo) {
                return "success";
            } else {
                return "fail";
            }
        } else {
            if($this->userInfo) {
                return "$this->callBackSuccess()";
            } else {
                return "$this->callBackFail()";
            }
        }
    }
}