<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_platform_check.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiPlatformCheckResponse</code>
 */
class ApiPlatformCheckResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool needRegister = 1;</code>
     */
    private $needRegister = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $needRegister
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Platform\ApiPlatformCheck::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool needRegister = 1;</code>
     * @return bool
     */
    public function getNeedRegister()
    {
        return $this->needRegister;
    }

    /**
     * Generated from protobuf field <code>bool needRegister = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setNeedRegister($var)
    {
        GPBUtil::checkBool($var);
        $this->needRegister = $var;

        return $this;
    }

}

