<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_payload.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>platform.ApiPushPayloadResponse</code>
 */
class ApiPushPayloadResponse extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Platform\ApiPushPayload::initOnce();
        parent::__construct($data);
    }

}

