<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: platform/api_push_check.proto

namespace Zaly\Proto\Platform;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 **
 * action: platform/api.push.check
 *
 * Generated from protobuf message <code>platform.ApiPushCheckRequest</code>
 */
class ApiPushCheckRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *sitePubkBase64 -> SHA1() / siteId
     *
     * Generated from protobuf field <code>string sitePubkId = 1;</code>
     */
    private $sitePubkId = '';
    /**
     * Generated from protobuf field <code>string siteUserToken = 2;</code>
     */
    private $siteUserToken = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $sitePubkId
     *          sitePubkBase64 -> SHA1() / siteId
     *     @type string $siteUserToken
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Platform\ApiPushCheck::initOnce();
        parent::__construct($data);
    }

    /**
     *sitePubkBase64 -> SHA1() / siteId
     *
     * Generated from protobuf field <code>string sitePubkId = 1;</code>
     * @return string
     */
    public function getSitePubkId()
    {
        return $this->sitePubkId;
    }

    /**
     *sitePubkBase64 -> SHA1() / siteId
     *
     * Generated from protobuf field <code>string sitePubkId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSitePubkId($var)
    {
        GPBUtil::checkString($var, True);
        $this->sitePubkId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string siteUserToken = 2;</code>
     * @return string
     */
    public function getSiteUserToken()
    {
        return $this->siteUserToken;
    }

    /**
     * Generated from protobuf field <code>string siteUserToken = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->siteUserToken = $var;

        return $this;
    }

}

